# Generated by Django 5.0.2 on 2024-02-22 23:19

from django.db import migrations


USERS_DATA = [
    {'username': "user1", 'password': "123456", 'first_name': "Usuario", 'last_name': "Um", 'limit': 100000},
    {'username': "user2", 'password': "123456", 'first_name': "Usuario", 'last_name': "Dois", 'limit': 80000},
    {'username': "user3", 'password': "123456", 'first_name': "Usuario", 'last_name': "Tres", 'limit': 1000000},
    {'username': "user4", 'password': "123456", 'first_name': "Usuario", 'last_name': "Quatro", 'limit': 10000000},
    {'username': "user5", 'password': "123456", 'first_name': "Usuario", 'last_name': "Cinco", 'limit': 500000},
]

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    user_model = apps.get_model("users", "User")
    for data in USERS_DATA:
        user_model.objects.create_user(**data)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    user_model = apps.get_model("users", "User")
    query = user_model.objects.all()
    for user in query:
        user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
