# Generated by Django 5.0.2 on 2024-02-22 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(verbose_name='valor')),
                ('transaction_type', models.CharField(choices=[('c', 'c'), ('d', 'd')], max_length=1, verbose_name='tipo')),
                ('description', models.CharField(max_length=10, verbose_name='descricao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
